export const meetings = [
  {
    id: 'MAC-203',
    title: 'Monthly Aerostat Coordination Review',
    date: '2026-05-25',
    time: '10:30',
    venue: 'Conference Hall A',
    priority: 'High',
    description: 'Review subsystem readiness, open agenda points, and cross-department dependencies.',
    attendees: ['MAC Secretariat', 'Para Head', 'Instrumentation', 'QA Cell', 'Flight Systems'],
  },
  {
    id: 'MAC-204',
    title: 'Payload Integration Readiness Meeting',
    date: '2026-05-29',
    time: '14:00',
    venue: 'Systems Lab Briefing Room',
    priority: 'Medium',
    description: 'Confirm payload integration schedule, test responsibilities, and documentation status.',
    attendees: ['Payload Team', 'Avionics', 'Safety Cell', 'Documentation Cell'],
  },
  {
    id: 'MAC-205',
    title: 'Procurement and Spares Follow-up',
    date: '2026-06-03',
    time: '11:15',
    venue: 'Admin Block Meeting Room',
    priority: 'Medium',
    description: 'Track procurement milestones for spares and vendor clarifications.',
    attendees: ['Admin', 'Stores', 'Finance', 'Technical Coordination'],
  },
  {
    id: 'MAC-206',
    title: 'Field Trial Documentation Closure',
    date: '2026-06-10',
    time: '09:45',
    venue: 'MAC Review Room',
    priority: 'Critical',
    description: 'Close pending documentation and approve report ownership for field trial observations.',
    attendees: ['Para Head', 'QA Cell', 'Flight Systems', 'Documentation Cell'],
  },
];
